# Generated by Django 3.2.7 on 2021-10-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0006_remove_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='swimming',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.PositiveIntegerField()),
                ('swim', models.PositiveIntegerField()),
                ('dive', models.PositiveIntegerField()),
                ('surf', models.PositiveIntegerField()),
                ('lounge', models.PositiveIntegerField()),
                ('boat', models.PositiveIntegerField()),
                ('clean', models.PositiveIntegerField()),
                ('safety', models.PositiveIntegerField()),
                ('lifeguard', models.BooleanField()),
                ('beach', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='beach.beach')),
            ],
        ),
    ]
