# Generated by Django 3.2.7 on 2021-10-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0007_auto_20211004_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='beach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beach.beach'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='boat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='clean',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dive',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lifeguard',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lounge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='safety',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='surf',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='swim',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
