# Generated by Django 3.2.7 on 2021-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0009_auto_20211004_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='boat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='clean',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='dive',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='lounge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='overall',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='safety',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='surf',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
