# Generated by Django 3.2.7 on 2021-10-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0010_auto_20211004_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='dive',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='lounge',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='safety',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='surf',
        ),
    ]
