# Generated by Django 3.2.7 on 2021-10-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0012_rating_dive'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='lounge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='surf',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
