# Generated by Django 3.2.7 on 2021-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0013_auto_20211004_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='boat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='clean',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
