# Generated by Django 3.2.7 on 2021-10-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0014_auto_20211004_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='clean',
            new_name='isClean',
        ),
        migrations.AddField(
            model_name='rating',
            name='lifeguard',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='safety',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='beach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='beach.beach'),
        ),
    ]
