# Generated by Django 3.2.7 on 2021-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0015_auto_20211004_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='img',
            field=models.ImageField(null=True, upload_to='beach_pic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default_user_pic.jpg', upload_to='profile_pic'),
        ),
    ]
