# Generated by Django 3.2.7 on 2021-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0018_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bucketList',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
