# Generated by Django 3.2.7 on 2021-11-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0020_auto_20211130_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='lifeguardRating',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lifeguard',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=3),
        ),
    ]
