# Generated by Django 3.2.7 on 2021-12-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0024_alter_beach_overallrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='boat',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dive',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='isClean',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lifeguard',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lounge',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='safety',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='surf',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='swim',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
    ]
